# .goreleaser.yml
# Build customization
builds:
  - main: ./main.go
    binary: helm-dashboard
    ldflags: -s -w -X github.com/komodorio/helm-dashboard/main.version={{.Version}} -X github.com/komodorio/helm-dashboard/main.commit={{.Commit}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - id: helm-dashboard
    format: tar.gz
    replacements:
      amd64: x86_64
      darwin: Darwin
      linux: Linux